### ISSUE TITLE
Not working with QGIS 3.16

### ISSUE THREAD

**Issue by AndyCoach** [MIERUNE/GTFS-GO#21]
Tried importing a valid GTFS zip file (I had successfully imported it using TransCAD earlier), no go, the plugin shows 0% complete after 15 min. GTFS file attached. Not a clue why it won't work. 
[6_repaired_zipped.zip](https://github.com/MIERUNE/GTFS-GO/files/5955822/6_repaired_zipped.zip)

**Comment by kenseii** [comment]
Hi @AndyCoach it seems your dataset is missing a calendar column which is normally [required](https://github.com/MIERUNE/GTFS-GO/blob/master/gtfs_parser/constants.py#L11) by the plugin.

The next release will be able to show the error message instead of just stopping at 0%.

If you want to still proceed without that column you can edit the constants.py file in your plugins folder to use calendar `False` then the import will go smoothly.

The required columns are based on this reference https://developers.google.com/transit/gtfs/reference

**Comment by takohei** [comment]
The feed is missing feed_info.txt and calendar.txt

We fixed on v3.2.3 by PR https://github.com/MIERUNE/GTFS-GO/pull/76
@Kanahiro Please close this issue.

![image](https://github.com/MIERUNE/GTFS-GO/assets/48475419/39069874-813a-461d-b7e2-cf5fb049cef3)

**Comment by Kanahiro** [comment]
thanks, close...
